// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'IconFaSolid:ellipsisV': typeof import('~icons/fa-solid/ellipsis-v')['default']
    'IconLa:language': typeof import('~icons/la/language')['default']
    'IconMdi:githubFace': typeof import('~icons/mdi/github-face')['default']
    'IconMdi:playCircleOutline': typeof import('~icons/mdi/play-circle-outline')['default']
    'IconMdi:stopCircleOutline': typeof import('~icons/mdi/stop-circle-outline')['default']
    'IconSimpleIcons:nuxtdotjs': typeof import('~icons/simple-icons/nuxtdotjs')['default']
    'IconUil:angleDown': typeof import('~icons/uil/angle-down')['default']
    'IconUil:apps': typeof import('~icons/uil/apps')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:clock': typeof import('~icons/uil/clock')['default']
    'IconUil:database': typeof import('~icons/uil/database')['default']
    'IconUil:laptop': typeof import('~icons/uil/laptop')['default']
    'IconUil:link': typeof import('~icons/uil/link')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:pause': typeof import('~icons/uil/pause')['default']
    'IconUil:play': typeof import('~icons/uil/play')['default']
    'IconUil:plus': typeof import('~icons/uil/plus')['default']
    'IconUil:puase': typeof import('~icons/uil/puase')['default']
    'IconUil:server': typeof import('~icons/uil/server')['default']
    'IconUil:stop': typeof import('~icons/uil/stop')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
  }
}

export {}
